### ISSUE TITLE
/healthcheck triggers HTTP_HEADERS_SENT error

### ISSUE THREAD

**Issue by claussian** [Zumata/generator-zumata-chatbot#19]
Sample logs:

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

**Comment by motss** [comment]
https://github.com/Zumata/generator-zumata-chatbot/blob/cc6d023b53f106097428fc9db31db70f8100395f/generators/app/templates/src/route/healthcheck.ts#L10

**Comment by motss** [comment]
@claussian Mind fixing this as well in the same PR?

**Comment by claussian** [comment]
Done.
